# Generated by Django 4.2.11 on 2024-06-11 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='image',
            field=models.ImageField(blank=True, default='media/default_img/user_img.png', null=True, upload_to='users_image/'),
        ),
    ]
