# Generated by Django 4.2.11 on 2024-06-26 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messageapp', '0006_alter_message_user'),
        ('messageapp', '0006_alter_notification_options_and_more'),
    ]

    operations = [
    ]
